name: univproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_otp_text_field: ^1.2.0
  syncfusion_flutter_pdfviewer: ^27.1.52
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  get: ^4.6.6
  intl: ^0.19.0
  date_picker_plus: ^4.1.0
  firebase_storage: ^12.3.4
  razorpay_flutter: ^1.3.7
  file_picker: ^8.1.3
  fluttertoast: ^8.2.8
  flutter_pdfview: ^1.3.4
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/changeroom.png
    - lib/assets/images/db.png
    - lib/assets/images/fee.png
    - lib/assets/images/menu.png
    - lib/assets/images/query.png
    - lib/assets/images/roomavail.png
    - lib/assets/images/logo.png
